# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb16c683999d9ea6c6fa5c1ca67b3ec17e32778067b11a4630f84b4ac973f958c91250941b0cea02e4b483ee149fabf51b4ba0fcc39ba17366a4a8609f4777ff

test:
  secret_key_base: 503574b9d6940675d8e25d859b28fe39791f6412708d9ec089dc445219eaae8124d61ba60d42f7cd3c43d1440d21be3fa5e3158c9fd578dd9625110a7849418d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
